package decemberlongchallenge.module.common.serviceinterface;

import decemberlongchallenge.uiview.common.SqlinjectionSDO;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 27 12:25:56 IST 2016
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace = "/decemberlongchallenge/module/common/", name = "AppModuleService",
                    wsdlLocation = "decemberlongchallenge/module/common/serviceinterface/AppModuleService.wsdl")
@SDODatabinding(schemaLocation = "decemberlongchallenge/module/common/serviceinterface/AppModuleService.xsd")
public interface AppModuleService {
    public static final String NAME = "{/decemberlongchallenge/module/common/}AppModuleService";

    @WebMethod(action = "/decemberlongchallenge/module/common/createSqlinjection1",
               operationName = "createSqlinjection1")
    @RequestWrapper(targetNamespace = "/decemberlongchallenge/module/common/types/", localName = "createSqlinjection1")
    @ResponseWrapper(targetNamespace = "/decemberlongchallenge/module/common/types/",
                     localName = "createSqlinjection1Response")
    @WebResult(name = "result")
    SqlinjectionSDO createSqlinjection1(@WebParam(mode = WebParam.Mode.IN, name = "sqlinjection1")
                                        SqlinjectionSDO sqlinjection1) throws ServiceException;

    @WebMethod(action = "/decemberlongchallenge/module/common/updateSqlinjection1",
               operationName = "updateSqlinjection1")
    @RequestWrapper(targetNamespace = "/decemberlongchallenge/module/common/types/", localName = "updateSqlinjection1")
    @ResponseWrapper(targetNamespace = "/decemberlongchallenge/module/common/types/",
                     localName = "updateSqlinjection1Response")
    @WebResult(name = "result")
    SqlinjectionSDO updateSqlinjection1(@WebParam(mode = WebParam.Mode.IN, name = "sqlinjection1")
                                        SqlinjectionSDO sqlinjection1) throws ServiceException;

    @WebMethod(action = "/decemberlongchallenge/module/common/deleteSqlinjection1",
               operationName = "deleteSqlinjection1")
    @RequestWrapper(targetNamespace = "/decemberlongchallenge/module/common/types/", localName = "deleteSqlinjection1")
    @ResponseWrapper(targetNamespace = "/decemberlongchallenge/module/common/types/",
                     localName = "deleteSqlinjection1Response")
    void deleteSqlinjection1(@WebParam(mode = WebParam.Mode.IN, name = "sqlinjection1")
                             SqlinjectionSDO sqlinjection1) throws ServiceException;
}

